### ISSUE TITLE
Naming issue for the transcriptome file when running `./simpleaf index`

### ISSUE THREAD

**Issue by naity2** [COMBINE-lab/usefulaf#4]
Dear Authors,

I'm having the follow issue when running `./simpleaf index`:
`The file [custome_index/ref//transcriptome_splici_fl86.fa] provided for the transcriptome does not appear to exist.`

The cause seems to be that the default value for the `filename_prefix` parameter of the `make_splici_txome` function is "splici", whereas the line `cmd="$salmon index -t $outref/transcriptome_splici_fl$fl.fa -i $outidx -p $threads $sparse_flag"` in the `usefulaf/bash/simpleaf` file has an extra prefix of "transcriptome". Moreoever, `./simpleaf index` doesn't provide a `--filename-prefix` parameter to get around this. Additionally, since `outref="$output/ref/"`, there is an extra "/" in the path.

Could you please help look into this?

Thanks very much!

**Comment by rob-p** [comment]
Cc @DongzeHE --- also, can you please do a full run through to ensure everything works as expected end-to-end? We'd done this but something must have changed. We need a regression test for this.

**Comment by DongzeHE** [comment]
sure! will test it now.

**Comment by DongzeHE** [comment]
Hi @naity2,

I have fixed the bug and given it an end-to-end run using a real dataset. Please do `git pull` to pull my latest changes. 

I am sorry for the inconvenience and thank you so much for bringing this issue up.

-Dongze

**Comment by naity2** [comment]
Thank you, @DongzeHE, for the prompt response!

Would you please kindly update the docker image as well? Thanks a lot!

**Comment by DongzeHE** [comment]
The docker image is updated. Enjoy. 😉

**Comment by naity2** [comment]
> The docker image is updated. Enjoy. 😉

Awesome, thank you so much!

**Comment by rob-p** [comment]
Hi @naity2,

  I just wanted to mention that we just released `pyroe` 0.6.0.  This version adds some new commands including `id-to-name` that can convert a `gene_id` to `gene_name` mapping from a GTF or GFF3 file, as well as a `convert` command that can convert an alevin-fry quantification directory to e.g. an AnnData or loom file.  The convert command can take an id to name mapping and apply the renaming during conversion.  In general, we've greatly improved the documentation for `pyroe`, which you can find [here](https://pyroe.readthedocs.io/en/latest/index.html).  Let us know if you have any questions.

Best,
Rob

**Comment by naity2** [comment]
> Hi @naity2,
> 
> I just wanted to mention that we just released `pyroe` 0.6.0. This version adds some new commands including `id-to-name` that can convert a `gene_id` to `gene_name` mapping from a GTF or GFF3 file, as well as a `convert` command that can convert an alevin-fry quantification directory to e.g. an AnnData or loom file. The convert command can take an id to name mapping and apply the renaming during conversion. In general, we've greatly improved the documentation for `pyroe`, which you can find [here](https://pyroe.readthedocs.io/en/latest/index.html). Let us know if you have any questions.
> 
> Best, Rob

Awesome, thank you so much for the very useful updates!
