### ISSUE TITLE
Error in install.packages("BiocManager") : unable to install packages

### ISSUE THREAD

**Issue by rob-p** [COMBINE-lab/usefulaf#7]
Issue [#86](https://github.com/COMBINE-lab/alevin-fry/issues/86) being moved from `alevin-fry` to here.  Originally posted by @ZeitgeberH,

Hi,
I was trying run this on a Ubuntu server.  Both directly downloaded image or one converted from docker gave the same error:
```
$ singularity exec --cleanenv --bind $AF_SAMPLE_DIR:/workdir --pwd /usefulaf/bash usefulaf_latest.sif ./simpleaf index -f /workdir/human_CR_3.0/fasta/genome.fa -g /workdir/human_CR_3.0/genes/genes.gtf -l 91 -t 16 -o /workdir/human_CR_3.0_splici
ALEVIN_FRY_HOME=/workdir/.afhome
salmon 1.8.0
salmon version 1.8.0 is sufficiently new.
alevin-fry 0.6.0
alevin-fry version 0.6.0 is sufficiently new.
/opt/conda/bin/time command appears to execute a valid GNU time

Extracting the splici reference using command

 Rscript build_splici_ref.R /workdir/human_CR_3.0/fasta/genome.fa /workdir/human_CR_3.0/genes/genes.gtf 91 /workdir/human_CR_3.0_splici/ref/    --filename-prefix splici

Warning in install.packages("BiocManager") :
  'lib = "/opt/conda/lib/R/library"' is not writable
Error in install.packages("BiocManager") : unable to install packages
Execution halted
```

**Comment by rob-p** [comment]
cc @DongzeHE — btw I think we should also probably update the docker image to use the newest salmon & alevin-fry.

**Comment by DongzeHE** [comment]
Right. 
- This is always the problem of using the default R on a remote server. 
AFAIK, this problem can be solved by setting an R path env variable by following [this R blog](https://www.r-bloggers.com/2020/10/customizing-your-package-library-location/) or this [post](https://stackoverflow.com/questions/15170399/change-r-default-library-path-using-libpaths-in-rprofile-site-fails-to-work). Or, if we want to avoid this problem in our side, we can set a temp lib dir before installing these missingpackages, though it means the users still need to figure out how to download the packages when they want to use the packages out of usefulaf.

    ```R
    .libPaths( c( "somewhere/in/the/working/dir" , .libPaths()))
    ```

- For the singularity error, I am a little bit confused. Why does it want to use the system's version of R and download the packages? Didn't we include R and the libraries in the singularity env? 


- For the docker image, yes, let's update it.

**Comment by HelenLindsay** [comment]
Hello,

I've been using the singularity container and ran into the same error.  I solved it by setting R_LIBS_USER. 
 Because of the "--cleanenv", I had to export it as a singularity environment variable before running the container, e.g.

```
export SINGULARITYENV_R_LIBS_USER="/path/to/local/R/library"

singularity exec --cleanenv \n
	        --bind $AF_SAMPLE_DIR:/workdir \
		--pwd /usefulaf/bash usefulaf_latest.sif \
	        ./simpleaf index \
		-f ${genome} \
		-g ${gtf} \
		-l 91 -t 8 -o /workdir/human_CR_3.0_splici
```

**Comment by rob-p** [comment]
Hi @ZeitgeberH,

Please see the discussion [here](https://github.com/COMBINE-lab/usefulaf/issues/8) and the new README for this repository. Basically, we've re-hauled and substantially improved the `usefulaf` docker/singularity images, and all of the original functionality provided by this repo has found more permanent and stable homes.  Please give the new image a try and let us know if it works for you.  If you run into any problems, please feel free to re-open this issue, or to open another.

Best,
Rob

**Comment by ZeitgeberH** [comment]
Hi @rob-p ,
The new singularity images works like a charm. Thanks for the update!
A quick question, is there an option to request Alevin-fry (or in `load_fry`) to get gene symbol as default, rather than Ensemble ID.

**Comment by rob-p** [comment]
With `pyroe` (which is also included in the image), you can use the combination of the conversion command (https://pyroe.readthedocs.io/en/latest/converting_quants.html) and the id-to-name mapping (https://pyroe.readthedocs.io/en/latest/geneid_to_name.html) commands to create a count matrix with gene names.
